apiVersion: apps/v1
kind: Deployment
metadata:
  name: station-ski-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stationski-app
  template:
    metadata:
      labels:
        app: stationski-app
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_DATABASE
              value: stationski
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              name: mysql-port
        - name: backend
          image: noursine/hannachinoursine-5arctic4-g1-stationski:0.0.2
          env:
            - name: DATABASE_URL
              value: jdbc:mysql://mysql-service:3306/stationski
          ports:
            - containerPort: 9060
              name: backend-port

---
# Service for the frontend
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: stationski-app  # Updated to match the app label in the deployment
  ports:
    - protocol: TCP
      port: 9060
      targetPort: 9060
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: stationski-app  # It should select the backend container as well
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---