apiVersion: apps/v1
kind: Deployment
metadata:
  name: station-ski-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stationski-app
  template:
    metadata:
      labels:
        app: stationski-app
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_DATABASE
              value: stationSki
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              name: mysql-port
        - name: backend
          image: marammanai/manaimaram-g1-stationski  # Suppression de l'espace dans le nom de l'image
          env:
            - name: DATABASE_URL
              value: jdbc:mysql://mysql-service:3306/stationSki  # Modifie localhost en mysql-service pour correspondre au service
          ports:
            - containerPort: 9001
              name: backend-port

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: stationski-app
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: stationski-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
