# templates/services.yaml

# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: stationski-app
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.servicePort }}
      targetPort: {{ .Values.mysql.servicePort }}

---

# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: stationski-app
  ports:
    - protocol: TCP
      port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.servicePort }}
      name: backend
